#!/bin/bash
#   _  _  _  _ 
#  (_)(_)(_)(_)
#  | || || || |
#  | || || || |
#  |_||_||_||_|
#
#    irc it, immensely improved
#    a wrapper for ii and tmux
#    written by thomas berryhill <tb01110100@gmail.com>
#    under the mit license

source ~/.ii/config || { echo "config file ~/.ii/config not found, aborting" >&2; exit 1; }

color5="$(colorconvert $ui_accent)"
endcolor="$(colorconvert end)"

case $1 in
  help|-h|--help|"")
    cat << EOF

iiii 0.1
written by tb01110100

usage: iiii [command] [options]

  ${color5}help${endcolor} - display this message

  ${color5}start${endcolor} - start instances of ii

  ${color5}stop${endcolor} - kill ii

EOF
    exit ;;
  start)
    [[ -z "$TMUX" ]] && { echo "please run this in a new tmux session" >&2; exit 1; }
  { [[ "$(tmux display-message -p \#S)" != "ii" ]] && tmux rename-session iiii
    tmux renamew iiii
    tmux set status on 
    tmux set status-position top
    tmux set status-bg black
    tmux set status-fg $ui_accent
    tmux set status-left ""
    tmux set status-right ""
    tmux set status-justify centre
    tmux set mouse-select-window on
    tmux set pane-border-style fg=$ui_accent
    tmux set pane-active-border-style fg=$ui_accent; } > /dev/null
    for network in "${autoconnect[@]}"; do
      "$network"
      while true; do
        rm "$iidir/$host/in"
        echo "connecting to $host"
        ii -i "$iidir" -s "$host" -p "$port" -n "$nick" &
        iipid="$!"
        until [[ -p "$iidir/$host/in" ]]; do sleep .1; done
        echo "successfully connected to $host"
        tmux neww -n "$network" "iiii-view $network"
        tmux splitw -l 2 "iiii-message $network"
        if [[ -n "$nickpass" ]]; then
          echo "attempting to identify to ${host}'s nickserv"
          echo "/j nickserv identify $nickpass" > "$iidir/$host/in"
          sleep 10
        fi
        echo "joining channels: ${autojoins[@]}"
        for channel in "${autojoins[@]}"; do
          echo "/j $channel" > "$iidir/$host/in"
          tmux neww -n "$channel" "iiii-view $network \\$channel"
          tmux splitw -l 2 "iiii-message $network \\$channel"
          sleep .5
        done
        unset host port autojoins nick nickpass
        nick="$(whoami)"
        wait "$iipid"
        echo "connection to $host lost, attempting to reconnect"
      done &
    done
    wait
    exit ;;
  stop)
    killall iiii ii || echo "something went wrong, feel free to troubleshoot <3" >&2
    exit ;;
esac
